### ISSUE TITLE
Relicensing part of the code as MIT.

### ISSUE THREAD

**Issue by ingenieroariel** [linklayer/pyvit#17]
Hello Eric,

I have taken parts of pyvit to create a single line parser targetted at compatibility with Comma AI's Open Pilot and later Autoware.

Since the code I am developing will be MIT I would like to kindly ask if I can use the code here: https://github.com/autti/veloz/commit/cce91b3ab95c3aa4bdbf4664f3990138b872ae46 under that license.

I would just import pyvit but then would have to change my codebase from MIT to GPL v3 and that may make contributions to Udacity's self driving car projects in the future more difficult (they are using MIT too).

**Comment by ericevenchick** [comment]
I'd rather not relicense at this time, but it might be advisable for you to use pyvit as a library, installed from pip, instead of copying the source into your own project. That would make for cleaner code and get rid of the licensing issues, as you could release your source as MIT with no issues, and have a requirements.txt file that installs pyvit (and any other dependancies).

**Comment by ingenieroariel** [comment]
Thanks for getting back to me. I'll switch to pyvit proper and submit any improvements back upstream.
